#!/usr/bin/with-contenv bash

# set timezone
echo "Setting timezone to $TZ."
cp -f "/usr/share/zoneinfo/${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone

# permissions
chown -R abc:abc /config
chown abc:abc /downloads
